const products = [
  {
    id: 1,
    name: "Sidda lepa",
    brand: "Sidda lepa",
    desc: "test",
    price: 0.2,
    image: "https://i.postimg.cc/XYgZw7ph/sale-sale-valentine-s-day-50-off.png",
  },
  {
    id: 2,
    name: "Sidda lepa ",
    brand: "Sidda lepa",
    desc: "test",
    price: 0.5,
    image: "https://i.postimg.cc/XYgZw7ph/sale-sale-valentine-s-day-50-off.png",
  },
  {
    id: 3,
    name: "Sidda lepa",
    brand: "Sidda lepa",
    desc: "test",
    price: 0.9,
    image: "https://i.postimg.cc/XYgZw7ph/sale-sale-valentine-s-day-50-off.png",
  },
  {
    id: 4,
    name: "Sidda lepa",
    brand: "Sidda lepa",
    desc: "test",
    price: 0.8,
    image: "https://i.postimg.cc/XYgZw7ph/sale-sale-valentine-s-day-50-off.png",
  },
  {
    id: 5,
    name: "Sidda lepa",
    brand: "Sidda lepa",
    desc: "test",
    price: 0.1,
    image: "https://i.postimg.cc/XYgZw7ph/sale-sale-valentine-s-day-50-off.png",
  },
  {
    id: 6,
    name: "Sidda lepa",
    brand: "Sidda lepa",
    desc: "test",
    price: 0.3,
    image: "https://i.postimg.cc/XYgZw7ph/sale-sale-valentine-s-day-50-off.png",
  },
  {
    id: 7,
    name: "Sidda lepa",
    brand: "Sidda lepa",
    desc: "test",
    price: 1.2,
    image: "https://i.postimg.cc/XYgZw7ph/sale-sale-valentine-s-day-50-off.png",
  },
  {
    id: 8,
    name: "Sidda lepa",
    brand: "Sidda lepa",
    desc: "test",
    price: 1.6,
    image: "https://i.postimg.cc/XYgZw7ph/sale-sale-valentine-s-day-50-off.png",
  },
  {
    id: 9,
    name: "Sidda lepa",
    brand: "Sidda lepa",
    desc: "test",
    price: 1.6,
    image: "https://i.postimg.cc/XYgZw7ph/sale-sale-valentine-s-day-50-off.png",
  },
  {
    id: 10,
    name: "Sidda lepa",
    brand: "Sidda lepa",
    desc: "test",
    price: 1.8,
    image: "https://i.postimg.cc/XYgZw7ph/sale-sale-valentine-s-day-50-off.png",
  },
  {
    id: 11,
    name: "Sidda lepa",
    brand: "Sidda lepa",
    desc: "test",
    price: 399,
    image: "https://i.postimg.cc/XYgZw7ph/sale-sale-valentine-s-day-50-off.png",
  },
  {
    id: 12,
    name: "Sidda lepa",
    brand: "Sidda lepa",
    desc: "test",
    price: 1.7,
    image: "https://i.postimg.cc/XYgZw7ph/sale-sale-valentine-s-day-50-off.png",
  },
  {
    id: 13,
    name: "Sidda lepa",
    brand: "Sidda lepa",
    desc: "test",
    price: 1.3,
    image: "https://i.postimg.cc/XYgZw7ph/sale-sale-valentine-s-day-50-off.png",
  },
  {
    id: 14,
    name: "Sidda lepa",
    brand: "Sidda lepa",
    desc: "test",
    price: 2,
    image: "https://i.postimg.cc/XYgZw7ph/sale-sale-valentine-s-day-50-off.png",
  },
  {
    id: 15,
    name: "Sidda lepa",
    brand: "Sidda lepa",
    desc: "test",
    price: 2.6,
    image: "https://i.postimg.cc/XYgZw7ph/sale-sale-valentine-s-day-50-off.png",
  },
  {
    id: 16,
    name: "Sidda lepa",
    brand: "Sidda lepa",
    desc: "test",
    price: 2.3,
    image: "https://i.postimg.cc/XYgZw7ph/sale-sale-valentine-s-day-50-off.png",
  },
  {
    id: 17,
    name: "Sidda lepa",
    brand: "Sidda lepa",
    desc: "test",
    price: 5,
    image: "https://i.postimg.cc/XYgZw7ph/sale-sale-valentine-s-day-50-off.png",
  },
  {
    id: 18,
    name: "Sidda lepa",
    brand: "Sidda lepa",
    desc: "test",
    price: 3,
    image: "https://i.postimg.cc/XYgZw7ph/sale-sale-valentine-s-day-50-off.png",
  },
 
 
];

module.exports = products;
